### ISSUE TITLE
Utility functions return false positives for empty collection

### ISSUE THREAD

**Issue by coopy** [FormidableLabs/victory-util#12]
I added some test coverage for the collection methods (https://github.com/FormidableLabs/victory-util/pull/11), and these cases failed:
```
expect(isArrayOfArrays([])).to.equal(false);
expect(containsStrings([])).to.equal(false);
```

https://github.com/FormidableLabs/victory-util/pull/11 has a fix, so if the expected behavior is to return `false` for empty arrays, we can merge #11.

/cc @boygirl

**Comment by boygirl** [comment]
@coopy yes, these should both return false. Thanks for catching that.

**Comment by coopy** [comment]
:+1:
